title: OSS_G6 C++ Algorithm Library Project
author: yhlim
email: yhlim1225@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is open source project for C++ modulized algorithm library.
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
remote_theme: thelehhman/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Open Source C++ Algorithm Library Project
  tagline: YJK, WSA, TYJ, YHL. 
  date_format: "%Y %b %-d"
  style: green
  showNav: true
  showPicker: false
  disqus_shortname: darkchoc

  # generate social links in footer
  social_links:
    github:  yhlim1225/OSS_G6
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

theme: jekyll-theme-cayman
